name: ci

on: [push, pull_request]

jobs:
  main:
    name: test (node ${{ matrix.node }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 13]

    steps:
      - name: checkout repo
        uses: actions/checkout@v1

      - name: use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        run: yarn

      - name: lint
        run: yarn lint
        env:
          CI: true

      - name: unit tests
        run: yarn test
        env:
          CI: true
